# https://github.com/meanbee/magedbm2/blob/fc8bbf9a97db2c27d0cd8a1153dda8c95b6f5996/etc/config.yml#L82
# https://github.com/DivanteLtd/anonymizer/blob/afac8e2f8f0ab49216ed1f5a6aca50bd13d67253/lib/anonymizer/project/basic/magento_2_0.json
tables:
- name: admin_user
  columns:
    firstname: firstname
    lastname: lastname
    email: email
    username: username
    password: password
- name: customer_entity
  columns:
    email: email
    firstname: firstname
    lastname: lastname
    vat_id: vat_number
- name: customer_address_entity
  columns:
    city: city
    company: company
    fax: telephone
    firstname: firstname
    lastname: lastname
    postcode: postcode
    street: street
    telephone: telephone
    vat_id: vat_number
- name: newsletter_subscriber
  columns:
    subscriber_email: email
    subscriber_confirm_code: md5
- name: quote
  columns:
    customer_email: email
    customer_prefix: title
    customer_firstname: firstname
    customer_middlename: firstname
    customer_lastname: lastname
    customer_suffix: customer_suffix
    customer_dob: datetime
    customer_note: note255
    remote_ip: ipv4
- name: quote_address
  columns:
    email: email
    prefix: title
    firstname: firstname
    lastname: lastname
    suffix: customer_suffix
    company: company
    street: street
    city: city
    region: state
    region_id: region_od
    postcode: postcode
    country_id: country_code
    telephone: telephone
    fax: telephone
    vat_id: vat_number
- name: rating_option_vote
  columns:
    remote_ip: ipv4
- name: review_detail
  columns:
    nickname: username
- name: sales_order
  columns:
    customer_dob: datetime
    customer_email: email
    customer_prefix: title
    customer_firstname: firstname
    customer_middlename: firstname
    customer_lastname: lastname
    customer_suffix: customer_suffix
    remote_ip: ipv4
    x_forwarded_for: ipv4
- name: sales_order_address
  columns:
    region: state
    postcode: postcode
    lastname: lastname
    street: street
    city: city
    email: email
    telephone: telephone
    firstname: firstname
    prefix: title
    middlename: firstname
    suffix: customer_suffix
    company: company
- name: sendfriend_log
  columns:
    ip: ipv4
eav:
- name: customer_entity_varchar
  attributes:
    firstname: firstname
    lastname: lastname
    taxvat: vat_number